# -*- coding: utf-8 -*-
"""DL4HProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tUH_nLzdYXCZ8w0Uq3KeLymAvkUyD6aq
"""

from google.colab import drive
drive.mount('/content/drive')

DATA_PATH = "/content/drive/MyDrive/DL4H/data_input_path/mimic/ADMISSIONS.csv"

descemb = 'descemb_rnn'

ratio = 100
value = 'VA'
task = 'mortality'
data = 'mimiciii'
WORLDSIZE = 1
input_path = '/content/drive/MyDrive/DL4H/data_output_path'

!python /content/drive/MyDrive/DL4H/DescEmb/main.py \
    --distributed_world_size {WORLDSIZE} \
    --input_path {input_path} \
    --model ehr_model \
    --embed_model $descemb \
    --pred_model transformer \
    --src_data {data} \
    --ratio {ratio} \
    --value_mode {value} \
    --task {task} \
    --n_epochs 20 \
    --seed 1 \
    --batch_size 128

!python /content/drive/MyDrive/DL4H/DescEmb/main.py \
    --distributed_world_size {WORLDSIZE} \
    --input_path {input_path} \
    --model ehr_model \
    --embed_model $descemb \
    --pred_model rnn \
    --src_data {data} \
    --ratio {ratio} \
    --value_mode {value} \
    --task 'readmission' \
    --n_epochs 20 \
    --seed 1 \
    --batch_size 128 \
    --patience 20

task = 'los_3day'

!python /content/drive/MyDrive/DL4H/DescEmb/main.py \
   python main.py \
  --distributed_world_size 1 \
  --input_path /path/to/data \
  --src_data mimiciii \
  --eval_data eicu \
  --model ehr_model \
  --embed_model descemb_rnn \
  --pred_model rnn \
  --task mortality \
  --n_epochs 20 \
  --seed 1 \
  --batch_size 128 \
  --transfer \
  --model_path /content/drive/MyDrive/DL4H/DescEmb/outputs/2025-04-22/mortality-wk/checkpoints/checkpoint_best.pt

!python /content/drive/MyDrive/DL4H/DescEmb/main.py \
  --distributed_world_size 1 \
  --input_path {input_path} \
  --src_data mimiciii \
  --eval_data eicu \
  --model ehr_model \
  --embed_model descemb_rnn \
  --pred_model rnn \
  --task mortality \
  --n_epochs 20 \
  --seed 1 \
  --batch_size 128 \
  --transfer \
  --model_path '/content/drive/MyDrive/DL4H/DescEmb/outputs/2025-04-22/mortality-wk/checkpoints/checkpoint_best.pt' \
  --patience 20